name: AutoRun

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Init project
        uses: actions/checkout@v2

      - name: Init environments
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install wget rsync imagemagick default-jre -y
          sudo mkdir -p .config/ripme
          sudo cp scripts/rip.properties .config/ripme/rip.properties

      - name: Run download_from_urls
        run: sudo bash download_from_author.sh

      - name: Run gen datasets
        run: sudo bash gen_datasets.sh

      - name: Upload data
        uses: actions/upload-artifact@v2
        with:
          name: nfsw
          path: data
          if-no-files-found: ignore

      - name: Delete data
        run: sudo rm -rf data

      - name: Upload debug data
        uses: actions/upload-artifact@v2
        with:
          name: debug
          path: .
